// apps/doctor-manhattan/pages/_app.tsx
import React from 'react';
import { AppProps } from 'next/app';
import Head from 'next/head';
import { ReactComponent as NxLogo } from '../public/nx-logo-white.svg';
import './styles.css';

const CustomApp = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Welcome to doctor-manhattan!</title>
      </Head>
      <div className="app">
        <h1>Welcome to doctor-manhattan!</h1>
        <header>
          <img
            width="450"
            src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
            alt=""
          />
        </header>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
};

export default CustomApp;

// apps/wild-hunt/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Config, Message } from '@waffle-charm/api-interfaces';

@Component({
  selector: 'waffle-charm-root',
  template: `
    <div style="text-align: center;">
      <h1>Welcome to wild-hunt!</h1>
      <img
        width="450"
        src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
      />
    </div>
    <div>Message: {{ hello$ | async | json }}</div>
    <div>Config: {{ config$ | async | json }}</div>
  `,
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  hello$ = this.http.get<Message>('/api/hello');
  config$ = this.http.get<Config>('/api/config');
  constructor(private http: HttpClient) {}
}

<div style="text-align: center;">
  <h1>Welcome to wild-hunt!</h1>
  <img
    width="450"
    src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
  />
</div>
<div>Message: {{ hello$ | async | json }}</div>
