// apps/wild-hunt/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { Config, SummonerDTO } from '@waffle-charm/api-interfaces';
import { ReplaySubject } from 'rxjs';

@Component({
  selector: 'waffle-charm-root',
  template: `
    <div>
      <h1>Welcome to wild-hunt!</h1>
      <img
        width="450"
        src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
      />
    </div>
    <mat-form-field>
      <mat-label>Summoner Name</mat-label>
      <input #summonerInput matInput />
    </mat-form-field>
    <button mat-button (click)="getSummoner(summonerInput.value)">
      Search
    </button>
    <pre>Summoner: {{ summoner$ | async | json }}</pre>
  `,
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  config$ = new ReplaySubject<Config>(1);
  summoner$ = new ReplaySubject<SummonerDTO>(1);

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.getConfig();
  }

  getConfig(): void {
    this.http
      .get<Config>('/api/config')
      .subscribe((value) => this.config$.next(value));
  }

  getSummoner(name: string): void {
    this.http
      .get<SummonerDTO>(`/api/summoner/${name}`)
      .subscribe((value) => this.summoner$.next(value));
  }
}

<div style="text-align: center;">
  <h1>Welcome to wild-hunt!</h1>
  <img
    width="450"
    src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
  />
</div>
<div>Message: {{ hello$ | async | json }}</div>

// apps/crow-storm/src/app/app.tsx
import React, { useEffect, useState } from 'react'
import { MatchlistDto, SummonerDTO } from '@waffle-charm/api-interfaces'
import './app.scss'

export const App = () => {
  const [summoner, setSummoner] = useState<SummonerDTO>(null)
  const [summonerName, setSummonerName] = useState('')
  const [matchHistory, setMatchHistory] = useState<MatchlistDto>(null)

  function getSummoner(e: React.FormEvent<HTMLFormElement>): void {
    e.preventDefault()
    fetch(`/api/summoner/${summonerName}`)
      .then((_) => _.json())
      .then((value) => {
        setSummoner(value)
      })
  }

  useEffect(() => {
    if (summoner) {
      fetch(`/api/match/${summoner.accountId}`)
        .then((_) => _.json())
        .then((value) => {
          setMatchHistory(value)
        })
    }
  }, [summoner])

  return (
    <div id="wrapper">
      <div>
        <h1>Welcome to crow-storm!</h1>
        <img
          width="450"
          src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png"
          alt=""
        />
      </div>
      <form onSubmit={getSummoner}>
        <input
          type="text"
          onChange={(event) => setSummonerName(event.target.value)}
        />
        <button type="submit">Search</button>
      </form>
      <pre>Summoner: {JSON.stringify(summoner, null, 4)}</pre>
      <pre>Match History: {JSON.stringify(matchHistory, null, 4)}</pre>
    </div>
  )
}

export default App
